# Generated by Django 2.0.2 on 2018-02-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('manufacture', models.CharField(max_length=200)),
                ('raiting', models.FloatField()),
                ('image_url', models.URLField()),
                ('parameters', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('raiting', models.FloatField()),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SaleVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.IntegerField(default=0)),
                ('special_parameters', models.CharField(default='{}', max_length=3000)),
                ('url', models.URLField(default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=2000)),
                ('raiting', models.DecimalField(decimal_places=4, max_digits=7)),
                ('self_pickup', models.BooleanField(default=False)),
                ('phones', models.CharField(max_length=200)),
                ('delivery_conditions', models.CharField(max_length=200)),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SubProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('raiting', models.FloatField()),
                ('description', models.TextField(default='')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('name', 'address')},
        ),
        migrations.AddField(
            model_name='salevariant',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Shop'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'manufacture')},
        ),
        migrations.AlterUniqueTogether(
            name='salevariant',
            unique_together={('product', 'shop')},
        ),
    ]
